/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package shopping.list;

import io.javalin.Javalin;

public class App {

    public static void main(String[] args) {
        Javalin app = Javalin.create()
            .enableStaticFiles("/public")
            .start(80);
        
        app.get("getArticle", ctx -> {

        });

        app.get("/save", ctx -> {
            System.out.println("Speichern!");
            ListManager.addList(ctx.queryParam("name"));
        });
    }
}
